[functions.pluggy-webhook]
verify_jwt = false

[functions.pluggy-create-token]
verify_jwt = true

[functions.pluggy-delete-item]
verify_jwt = true

[functions.pluggy-get-api-key]
verify_jwt = true

[functions.pluggy-send-mfa]
verify_jwt = true

[functions.pluggy-sync-item]
verify_jwt = true

[functions.pluggy-sync-transactions]
verify_jwt = true

[functions.pluggy-update-item]
verify_jwt = true

[functions.reset-password-redirect]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.walts-analysis]
verify_jwt = true

[functions.walts-agent]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.connect-bank]
verify_jwt = false

[functions.get-market-data]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false